# Permalinks
permalink:           pretty

# Setup
title:               Jon Chu
tagline:             Blogs and bogs
url:                 http://jonjonchu.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Jon Chu
  url:               https://133890.co
  email:             jon@133890.co

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jon.jon.chu

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
